### ISSUE TITLE
Multiple USB Cameras

### ISSUE THREAD

**Issue by Morrious** [tensorfactory/PiFaceCam#4]
The Raspberry Pi 4B has 4 USB ports, but PiFaceCam is limited to just the first USB camera it sees. During initialization it indicates "USB camera found at index[0]". Is it possible to add an input for USB camera index, which would allow me to create multiple instances of PiFaceCam, each with a different USB camera?

**Comment by tensorfactory** [comment]
Hi Morrious,
  The initial versions of PiFaceCam actually required the user to input which camera index to use. However, we soon encountered the problem of RPI does not always assign the same camera index to the same USB camera (may change after each reboot). Because of this, we resort to have PiFaceCam auto-detect the first USB camera.
  FYI, our initial plan was also to use 2 USB cameras for the "stereo cameras setup" but encounter significant "frames drop" in one of the USB cameras. We are not able to resolve this despite having a separate process for each USB camera. 
 

Rgds

KC Yee

**Comment by Morrious** [comment]
Thank you for the reply. So unfortunately it seems like it is a limitation with the Raspberry Pi processing. or the USB interface on the Pi.
